# 1. Import Libraries

In [2]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Classification Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression

# Evaluation Metrics
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score
# Model Saving
import joblib

In [3]:
print("Libraries imported successfully.")

Libraries imported successfully.

## 2: Loading the Dataset

In [4]:
df = pd.read_csv("../data/Delhi Accident Data.csv")
# Display first 5 rows
df.head()

C:\Users\moham\AppData\Local\Temp\ipykernel_9556\3893790449.py:1: DtypeWarning: Columns (0: Unnamed: 9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/Delhi Accident Data.csv")

,YEAR,DISTRICT,VEHICLE AT FAULT,VICTIM,TYPE OF ACCIDENT,# INJURED,# KILLED,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,2008,NORTH WEST DELHI,UNKNOWN,CAR,FATAL ACCIDENT,0,1,NaN,NaN,NaN
1,2008,NORTH WEST DELHI,UNKNOWN,CYCLE,SIMPLE ACCIDENT,1,0,NaN,NaN,NaN
2,2008,NEW DELHI,HTV/GDS,PEDESTRIAN,FATAL ACCIDENT,0,1,NaN,NaN,NaN
3,2008,EAST DELHI,S/C&M/C,PEDESTRIAN,SIMPLE ACCIDENT,1,0,NaN,NaN,NaN
4,2008,SHAHDARA,S/C&M/C,PEDESTRIAN,SIMPLE ACCIDENT,1,0,NaN,NaN,NaN

In [5]:
# Shape of the dataset
print("Rows and Columns:", df.shape)

Rows and Columns: (75748, 10)

In [6]:
# Column names
print(df.columns.tolist())

['YEAR', 'DISTRICT', 'VEHICLE AT FAULT', 'VICTIM', 'TYPE OF ACCIDENT', '# INJURED', '# KILLED ', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

In [7]:
# Basic information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75748 entries, 0 to 75747
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   YEAR              75748 non-null  int64
 1   DISTRICT          75748 non-null  str
 2   VEHICLE AT FAULT  75748 non-null  str
 3   VICTIM            75748 non-null  str
 4   TYPE OF ACCIDENT  75748 non-null  str
 5   # INJURED         75748 non-null  int64
 6   # KILLED          75748 non-null  int64
 7   Unnamed: 7        0 non-null      float64
 8   Unnamed: 8        0 non-null      float64
 9   Unnamed: 9        1 non-null      str
dtypes: float64(2), int64(3), str(5)
memory usage: 5.8 MB

In [8]:
# Statistical summary
df.describe(include="all")

,YEAR,DISTRICT,VEHICLE AT FAULT,VICTIM,TYPE OF ACCIDENT,# INJURED,# KILLED,Unnamed: 7,Unnamed: 8,Unnamed: 9
count,75748.000000,75748,75748,75748,75748,75748.000000,75748.000000,0.0,0.0,1
unique,NaN,13,34,41,3,NaN,NaN,NaN,NaN,1
top,NaN,SOUTH EAST DELHI,PVT CAR,PEDESTRIAN,SIMPLE ACCIDENT,NaN,NaN,NaN,NaN,
freq,NaN,10096,22043,31872,55883,NaN,NaN,NaN,NaN,1
mean,2012.446863,NaN,NaN,NaN,NaN,0.955682,0.248640,NaN,NaN,NaN
std,2.868879,NaN,NaN,NaN,NaN,0.840229,0.450093,NaN,NaN,NaN
min,2008.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,2010.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN
50%,2013.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN
75%,2015.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN
max,2017.000000,NaN,NaN,NaN,NaN,30.000000,6.000000,NaN,NaN,NaN

## 3. Data Cleaning

Cleaned the dataset by:
- Removing unnecessary columns
- Removing extra spaces from column names
- Checking for missing values
- Checking for duplicate records

In [9]:
df.columns = df.columns.str.strip()

In [10]:
print(df.columns.tolist())

['YEAR', 'DISTRICT', 'VEHICLE AT FAULT', 'VICTIM', 'TYPE OF ACCIDENT', '# INJURED', '# KILLED', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

In [11]:
## Removing unnecessary columns
df.drop(columns=["Unnamed: 7", "Unnamed: 8", "Unnamed: 9"], inplace=True)

In [12]:
print(df.columns.tolist())

['YEAR', 'DISTRICT', 'VEHICLE AT FAULT', 'VICTIM', 'TYPE OF ACCIDENT', '# INJURED', '# KILLED']

In [13]:
df.isnull().sum()

YEAR                0
DISTRICT            0
VEHICLE AT FAULT    0
VICTIM              0
TYPE OF ACCIDENT    0
# INJURED           0
# KILLED            0
dtype: int64

In [14]:
## duplicates
duplicate_count = df.duplicated().sum()
print(f"Duplicate Rows: {duplicate_count}")

Duplicate Rows: 56819

In [15]:
print("Dataset Shape:", df.shape)

Dataset Shape: (75748, 7)

# 4. Feature Engineering

Preparing the dataset for classification by:

- Creating a new target variable (`TARGET`)
- Separating features and target
- Encoding categorical features into numerical values

In [16]:
# Create binary target
df["TARGET"] = (df["# INJURED"] > 0).astype(int)

# Display first few rows
df[["# INJURED", "TARGET"]].head(10)

   # INJURED  TARGET
0          0       0
1          1       1
2          0       0
3          1       1
4          1       1
5          1       1
6          2       1
7          1       1
8          1       1
9          1       1

In [17]:
df["TARGET"].value_counts()

TARGET
1    58938
0    16810
Name: count, dtype: int64

In [18]:
X = df.drop(columns=["# INJURED", "# KILLED", "TARGET"])
y = df["TARGET"]

In [19]:
label_encoders = {}

categorical_columns = X.select_dtypes(include="object").columns

for col in categorical_columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    label_encoders[col] = le

C:\Users\moham\AppData\Local\Temp\ipykernel_9556\1970755098.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(include="object").columns

In [20]:
X.head()

   YEAR  DISTRICT  VEHICLE AT FAULT  VICTIM  TYPE OF ACCIDENT
0  2008         5                33       6                 0
1  2008         5                33       9                 2
2  2008         2                17      25                 0
3  2008         1                23      25                 2
4  2008         7                23      25                 2

In [21]:
X.head()

   YEAR  DISTRICT  VEHICLE AT FAULT  VICTIM  TYPE OF ACCIDENT
0  2008         5                33       6                 0
1  2008         5                33       9                 2
2  2008         2                17      25                 0
3  2008         1                23      25                 2
4  2008         7                23      25                 2

In [22]:
joblib.dump(label_encoders, "../models/label_encoders_classifier.pkl")

['../models/label_encoders_classifier.pkl']

# 5. Train-Test Split

The dataset is divided into training and testing sets.

- Training set (80%) is used to train the model.
- Testing set (20%) is used to evaluate the model on unseen data.

The `stratify` parameter ensures that both sets maintain the same proportion of injury and no-injury cases.

In [23]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [24]:
print("Training Features:", X_train.shape)
print("Testing Features :", X_test.shape)
print("Training Labels  :", y_train.shape)
print("Testing Labels   :", y_test.shape)

Training Features: (60598, 5)
Testing Features : (15150, 5)
Training Labels  : (60598,)
Testing Labels   : (15150,)

In [25]:
print("Training Class Distribution")
print(y_train.value_counts())

print("\nTesting Class Distribution")
print(y_test.value_counts())

Training Class Distribution
TARGET
1    47150
0    13448
Name: count, dtype: int64

Testing Class Distribution
TARGET
1    11788
0     3362
Name: count, dtype: int64

# 6. Decision Tree Classifier

A Decision Tree Classifier is trained to predict whether an accident will result in injuries.

The model is evaluated using:
- Accuracy
- F1 Score
- Confusion Matrix
- Classification Report

In [26]:
# Create the Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(
    random_state=42,
    max_depth=5
)

# Train the model
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [27]:
# Predict on test data
y_pred_dt = dt_classifier.predict(X_test)

In [28]:
# Accuracy
dt_accuracy = accuracy_score(y_test, y_pred_dt)

# F1 Score
dt_f1 = f1_score(y_test, y_pred_dt)

print(f"Accuracy : {dt_accuracy:.4f}")
print(f"F1 Score : {dt_f1:.4f}")

Accuracy : 0.9601
F1 Score : 0.9737

In [29]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

[[ 3362     0]
 [  605 11183]]

In [30]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.95     15150
weighted avg       0.97      0.96      0.96     15150

In [31]:
dt_gmean = geometric_mean_score(y_test, y_pred_dt)

print(f"Accuracy : {dt_accuracy:.4f}")
print(f"F1 Score : {dt_f1:.4f}")
print(f"G-Mean   : {dt_gmean:.4f}")

Accuracy : 0.9601
F1 Score : 0.9737
G-Mean   : 0.9740

## Decision Tree Evaluation

The Decision Tree Classifier achieved strong performance on the test dataset with an **Accuracy of 96.01%**, **F1 Score of 97.37%**, and **G-Mean of 97.40%**. The confusion matrix showed **0 false positives** and only **605 false negatives**, indicating that the model correctly classified the majority of accident records. Overall, the model demonstrated excellent predictive performance and serves as a strong baseline for comparison with AdaBoost and Stacking classifiers.

## 7. AdaBoost Classifier

AdaBoost (Adaptive Boosting) is an ensemble learning algorithm that combines multiple weak learners, typically shallow decision trees, to create a stronger classifier.

In [32]:
# Create AdaBoost Classifier
ada_classifier = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

# Train the model
ada_classifier.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [33]:
# Predict on test data
y_pred_ada = ada_classifier.predict(X_test)

In [34]:
# Accuracy
ada_accuracy = accuracy_score(y_test, y_pred_ada)

# F1 Score
ada_f1 = f1_score(y_test, y_pred_ada)

# G-Mean
ada_gmean = geometric_mean_score(y_test, y_pred_ada)

print(f"Accuracy : {ada_accuracy:.4f}")
print(f"F1 Score : {ada_f1:.4f}")
print(f"G-Mean   : {ada_gmean:.4f}")

Accuracy : 0.9601
F1 Score : 0.9737
G-Mean   : 0.9740

In [35]:
cm_ada = confusion_matrix(y_test, y_pred_ada)

print(cm_ada)

[[ 3362     0]
 [  605 11183]]

In [36]:
print(classification_report(y_test, y_pred_ada))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.95     15150
weighted avg       0.97      0.96      0.96     15150

## AdaBoost Evaluation

The AdaBoost Classifier achieved an **Accuracy of 96.01%**, an **F1 Score of 97.37%**, and a **G-Mean of 97.40%** on the test dataset. The confusion matrix showed **0 false positives** and **605 false negatives**, producing the same classification performance as the Decision Tree Classifier. This indicates that AdaBoost did not provide a measurable improvement on this dataset, suggesting that the Decision Tree had already learned the underlying patterns effectively.

## 8. Random forest Classifier

In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score

In [38]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [39]:
y_pred_rf = rf_model.predict(X_test)

In [40]:
accuracy = accuracy_score(y_test, y_pred_rf)
f1 = f1_score(y_test, y_pred_rf)
gmean = geometric_mean_score(y_test, y_pred_rf)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"G-Mean: {gmean:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_rf))

print("\nClassification Report")
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.9525
F1 Score: 0.9691
G-Mean: 0.9492

Confusion Matrix
[[ 3171   191]
 [  528 11260]]

Classification Report
              precision    recall  f1-score   support

           0       0.86      0.94      0.90      3362
           1       0.98      0.96      0.97     11788

    accuracy                           0.95     15150
   macro avg       0.92      0.95      0.93     15150
weighted avg       0.96      0.95      0.95     15150

### Random Forest Evaluation

The Random Forest Classifier was trained and evaluated on the accident dataset to classify whether an accident would result in injuries. Random Forest is an ensemble learning algorithm that builds multiple decision trees using different subsets of the training data and combines their predictions through majority voting to improve generalization and reduce overfitting.

The model achieved the following performance:

- Accuracy: **95.25%**
- F1 Score: **96.91%**
- G-Mean: **94.92%**

The confusion matrix indicates that the model correctly classified most accident records, with **3,171 True Negatives**, **11,260 True Positives**, **191 False Positives**, and **528 False Negatives**.

Although the Random Forest Classifier demonstrated strong classification performance, its Accuracy, F1 Score, and G-Mean were slightly lower than those achieved by the Decision Tree and AdaBoost classifiers on this dataset. Therefore, while Random Forest proved to be an effective classifier, it was not selected as the best-performing model for this project. The results obtained from this model will be compared with the remaining classifiers to identify the most suitable model for accident injury prediction.

# 9. Support Vector Machine Classifier

In [41]:
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score

In [42]:
svm_model = LinearSVC(
    random_state=42,
    max_iter=5000
)

svm_model.fit(X_train, y_train)

LinearSVC(max_iter=5000, random_state=42)

In [43]:
y_pred_svm = svm_model.predict(X_test)

In [44]:
accuracy = accuracy_score(y_test, y_pred_svm)
f1 = f1_score(y_test, y_pred_svm)
gmean = geometric_mean_score(y_test, y_pred_svm)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"G-Mean: {gmean:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_svm))

print("\nClassification Report")
print(classification_report(y_test, y_pred_svm))

Accuracy: 0.9418
F1 Score: 0.9621
G-Mean: 0.9329

Confusion Matrix
[[ 3084   278]
 [  604 11184]]

Classification Report
              precision    recall  f1-score   support

           0       0.84      0.92      0.87      3362
           1       0.98      0.95      0.96     11788

    accuracy                           0.94     15150
   macro avg       0.91      0.93      0.92     15150
weighted avg       0.94      0.94      0.94     15150

## Support Vector Machine (SVM) Evaluation

The Support Vector Machine (SVM) classifier was trained and evaluated on the accident dataset to classify whether an accident would result in injuries. SVM is a supervised machine learning algorithm that finds the optimal hyperplane to separate different classes while maximizing the margin between them. For this project, a Linear Support Vector Machine (LinearSVC) was used due to its efficiency on large datasets.

The model achieved:

- Accuracy: 94.18%
- F1 Score: 96.21%
- G-Mean: 93.29%

The confusion matrix indicates:

- 3084 True Negatives
- 11184 True Positives
- 278 False Positives
- 604 False Negatives

Although the SVM classifier produced good classification performance with a high F1 Score, its overall Accuracy and G-Mean were lower than those of the Decision Tree and AdaBoost classifiers. Therefore, it was not selected as the best-performing model for this accident prediction project.

# 10. CatBoost Classifier

In [45]:
from catboost import CatBoostClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)
from imblearn.metrics import geometric_mean_score

In [46]:
cat_model = CatBoostClassifier(
    iterations=300,
    learning_rate=0.1,
    depth=6,
    random_seed=42,
    verbose=0
)

cat_model.fit(X_train, y_train)

CatBoostClassifier(depth=6, iterations=300, learning_rate=0.1, random_seed=42, verbose=0)

In [47]:
y_pred_cat = cat_model.predict(X_test)

In [48]:
accuracy = accuracy_score(y_test, y_pred_cat)
f1 = f1_score(y_test, y_pred_cat)
gmean = geometric_mean_score(y_test, y_pred_cat)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"G-Mean: {gmean:.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_cat))

print("\nClassification Report")
print(classification_report(y_test, y_pred_cat))

Accuracy: 0.9591
F1 Score: 0.9731
G-Mean: 0.9691

Confusion Matrix
[[ 3320    42]
 [  578 11210]]

Classification Report
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.94     15150
weighted avg       0.96      0.96      0.96     15150

## Catboost Classifier Evaluation 

Accuracy: 0.9591
F1 Score: 0.9731
G-Mean: 0.9691

Confusion Matrix
[[ 3320    42]
 [  578 11210]]

Classification Report
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.94     15150
weighted avg       0.96      0.96      0.96     15150

# 10. Stacking Classifier

The Stacking Classifier is an ensemble learning technique that combines the predictions of multiple base classifiers using a meta-classifier. In this project, a Decision Tree Classifier and an AdaBoost Classifier are used as the base learners, while Logistic Regression is used as the final estimator. The model is evaluated using Accuracy, F1 Score, G-Mean, Confusion Matrix, and Classification Report.

In [49]:
## IMPORTING 
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [50]:
# Base models
estimators = [
    ("decision_tree", DecisionTreeClassifier(max_depth=5, random_state=42)),
    ("adaboost", AdaBoostClassifier(n_estimators=100, random_state=42)),
    ("random_forest", RandomForestClassifier(n_estimators=100, random_state=42)),
    ("catboost", CatBoostClassifier(
        iterations=300,
        learning_rate=0.1,
        depth=6,
        random_seed=42,
        verbose=0
    ))
]
# Stacking Classifier
stack_classifier = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(max_iter=1000),
    cv=5,
    n_jobs=-1
)

# Train the model
stack_classifier.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('decision_tree',
                                DecisionTreeClassifier(max_depth=5,
                                                       random_state=42)),
                               ('adaboost',
                                AdaBoostClassifier(n_estimators=100,
                                                   random_state=42)),
                               ('random_forest',
                                RandomForestClassifier(random_state=42)),
                               ('catboost',
                                CatBoostClassifier(depth=6, iterations=300, learning_rate=0.1, random_seed=42, verbose=0))],
                   final_estimator=LogisticRegression(max_iter=1000),
                   n_jobs=-1)

In [51]:
# Predict on test data
y_pred_stack = stack_classifier.predict(X_test)

In [52]:
# Accuracy
stack_accuracy = accuracy_score(y_test, y_pred_stack)

# F1 Score
stack_f1 = f1_score(y_test, y_pred_stack)

# G-Mean
stack_gmean = geometric_mean_score(y_test, y_pred_stack)

print(f"Accuracy : {stack_accuracy:.4f}")
print(f"F1 Score : {stack_f1:.4f}")
print(f"G-Mean   : {stack_gmean:.4f}")

Accuracy : 0.9591
F1 Score : 0.9731
G-Mean   : 0.9686

In [53]:
cm_stack = confusion_matrix(y_test, y_pred_stack)

print(cm_stack)

[[ 3315    47]
 [  572 11216]]

In [54]:
print(classification_report(y_test, y_pred_stack))

              precision    recall  f1-score   support

           0       0.85      0.99      0.91      3362
           1       1.00      0.95      0.97     11788

    accuracy                           0.96     15150
   macro avg       0.92      0.97      0.94     15150
weighted avg       0.96      0.96      0.96     15150

## Stacking Classifier Evaluation

The Stacking Classifier was developed by combining **Decision Tree, AdaBoost, Random Forest, and CatBoost** as the base learners, while **Logistic Regression** was used as the meta-classifier. The purpose of stacking was to improve classification performance by integrating the predictions of multiple machine learning models into a single ensemble.

The model achieved an **Accuracy of 95.91%**, an **F1 Score of 97.31%**, and a **G-Mean of 96.86%**, indicating excellent overall classification performance. The confusion matrix showed that the model correctly classified **3,315 non-injury cases** and **11,216 injury cases**, while incorrectly classifying **47 non-injury cases as injury** and **572 injury cases as non-injury**.

The classification report shows that the model achieved a **precision of 85%**, **recall of 99%**, and **F1 Score of 91%** for the non-injury class. For the injury class, it achieved **100% precision**, **95% recall**, and an **F1 Score of 97%**. The weighted average **F1 Score of 96%** demonstrates that the classifier maintained strong performance despite the class imbalance in the dataset.

Although the Stacking Classifier achieved excellent predictive performance, it did not outperform the standalone Decision Tree and AdaBoost classifiers. This is because the ensemble consisted primarily of tree-based models, which produced highly similar predictions. As a result, the Logistic Regression meta-classifier had limited additional information to learn from, resulting in only marginal improvements over individual classifiers. Nevertheless, the Stacking Classifier remains a robust ensemble model and demonstrates the effectiveness of combining multiple classifiers for accident injury prediction.

In [55]:
joblib.dump(dt_classifier,
            "../models/decision_tree_classifier.pkl")

['../models/decision_tree_classifier.pkl']